#! /bin/bash
#
# Helper script for KinKal_build  - build either prof or debug
#
# This is a separate script, not a bash function so that it will
# run in a sub-shell and not modify the environment of its parent shell.
#
# Environment variables used:
# CMAKEVER       = version + qualifer string for cmake
# ROOTVER        = version + qualifier string for root
# NBUILDTHREADS  = number of threads to use for make
# DOTESTS        = if true then do the tests after the build

# cmake and ups spell build types differently; do the translation
cmake_build_type=""
ups_build_type=""
if grep -q "prof"  <<< "$ROOTVER"; then
  cmake_build_type="Release"
  ups_build_type="prof"
elif grep -q "$debug"  <<< "$ROOTVER"; then
  cmake_build_type="Debug"
  ups_build_type="debug"
else
  echo "Could not understand requested build type derived from the ups ROOT product"
  echo "The ups root version is: " $ROOTVER
  exit 1
fi

echo "

  Begin ${ups_build_type} build

"

setup mu2e
setup cmake ${CMAKEVER}
if [[ "$?" != "0" ]]; then
  exit 2
fi
setup -B root ${ROOTVER}
if [[ "$?" != "0" ]]; then
  exit 3
fi
ups active

mkdir build_${ups_build_type}
cd build_${ups_build_type}
cmake ../KinKal  -DCMAKE_BUILD_TYPE=${cmake_build_type}
if [[ "$?" != "0" ]]; then
  exit 4
fi

make -j ${NBUILDTHREADS}
if [[ "$?" != "0" ]]; then
  exit 5
fi

if [[ -n "${DOTEST}" ]]; then
  make -j ${NBUILDTHREADS} test
  if [[ "$?" != "0" ]]; then
    exit 6
  fi
fi

exit 0
