#! /bin/bash
#
# Copy the files from the source and build areas to create a UPS product.
#
# This script unconditionally deletes previously existing installs of the
# same product+version+qualifiers: use with care.
#

PACKAGE_NAME=KinKal

# Check that the target UPS repo has been defined; if not provide a default.
if [ "${PRODUCTS_INSTALL}" = '' ];then
   PRODUCTS_INSTALL=${PWD}/artexternals
fi

# Where to find the files in the installer package
KINKAL_TO_UPS_DIR=`dirname $(readlink -f $0)`

# Intialize UPS repo if needed.
if ! [ -e ${PRODUCTS_INSTALL} ]; then
  mkdir ${PRODUCTS_INSTALL}
  cp -r ${KINKAL_TO_UPS_DIR}/.upsfiles ${PRODUCTS_INSTALL}
  cp -r ${KINKAL_TO_UPS_DIR}/.updfiles ${PRODUCTS_INSTALL}
fi

# Need this for get-directory-name
setup cetpkgsupport

if [ "${PACKAGE_SOURCE}" = '' ];then
   PACKAGE_SOURCE=${PWD}/${PACKAGE_NAME}
fi

# There are two representations of operating system UPS flavor:
# old style, for example: Linux64bit+2.6-2.12_e7
# new style, for example: slf6.x86_64
# We need them both.
old_flavour=`ups flavor -4`
new_flavour=`get-directory-name subdir`

# Build the names of the directories into which we will write things
tmp_with_dots=`echo ${EXTRA_ROOT_QUALIFIERS} | sed 's/:/./g'`
fq=${new_flavour}.${COMPILER_CODE}.${DEBUG_LEVEL}${tmp_with_dots}
topdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}
proddir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}
verdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}.version
bindir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}/${fq}
incdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}/include
upsdir=${PRODUCTS_INSTALL}/${PACKAGE_NAME}/${PACKAGE_VERSION}/ups

# I am not sure what this file is properly called.
# I am calling it the fqfile, which is short for flavor qualifier file.
tmp_with_underscore=`echo ${EXTRA_ROOT_QUALIFIERS} | sed 's/:/_/g'`
fqfile=${verdir}/${old_flavour}_${COMPILER_CODE}_${DEBUG_LEVEL}${tmp_with_underscore}

# Make directories, if needed.
if ! [ -e ${topdir} ];then
  mkdir ${topdir}
fi

if ! [ -e ${proddir} ];then
  mkdir ${proddir}
fi

if ! [ -e ${verdir} ];then
  mkdir ${verdir}
fi

# Remove all content that we will recreate.
# (Re)create required directories.
if [ -e ${bindir} ];then
  /bin/rm -rf ${bindir}
fi
mkdir ${bindir}

if [ -e ${incdir} ];then
  /bin/rm -rf ${incdir}
fi
mkdir ${incdir}

if [ -e ${upsdir} ];then
  /bin/rm -rf ${upsdir}
fi
mkdir ${upsdir}

if [ -e ${fqfile} ];then
  /bin/rm -rf ${fqfile}
fi

# Copy the required parts of the source directory to the installation area:

# Header files:
rsync -ar --exclude-from  ${KINKAL_TO_UPS_DIR}/exclude_for_include.txt \
    ${PACKAGE_SOURCE} ${proddir}/include

# UPS table file
${KINKAL_TO_UPS_DIR}/installTableFile ${upsdir}/${PACKAGE_NAME}.table

# Libaries and executable binaries
rsync -ar build_prof/lib ${bindir}
rsync -ar build_prof/bin ${bindir}

# A copy of the full source
rsync -ar --exclude-from  ${KINKAL_TO_UPS_DIR}/exclude_for_source.txt \
  ${PACKAGE_SOURCE} ${proddir}/source

# Create the ups fq file.
cat > ${fqfile} <<EOF
FILE = version
PRODUCT = ${PACKAGE_NAME}
VERSION = ${PACKAGE_VERSION}

#*************************************************
#
FLAVOR = ${old_flavour}
QUALIFIERS = "${COMPILER_CODE}:${DEBUG_LEVEL}${EXTRA_ROOT_QUALIFIERS}"
  DECLARER = `whoami`
  DECLARED = `date +"%Y-%m-%d %H:%M:%S GMT" -u`
  MODIFIER = `whoami`
  MODIFIED = `date +"%Y-%m-%d %H:%M:%S GMT" -u`
  PROD_DIR = ${PACKAGE_NAME}/${PACKAGE_VERSION}
  UPS_DIR = ups
  TABLE_FILE = ${PACKAGE_NAME}.table

EOF

unset old_flavour
unset new_flavour
unset fq
unset topdir
unset proddir
unset verdir
unset bindir
unset incdir
unset upsdir
unset fqfile
unset tmp_with_dots
unset tmp_with_underscore
